### ISSUE TITLE
Duping crystals

### ISSUE THREAD

**Issue by Aeroxia** [NPException/Dimensional-Pockets#101]
**Dimensional Pockets Version:**

> DimensionalPockets-1.7.10-0.11.4.1-universal

**MinecraftForge Version:**

> 10.13.4.1558

**SSP or SMP? (Client or Server):**

> Both

**Crash Report (via. Pastebin):**

> N/A

**What happens / happened?:**

> Infinite end/nether crystal dupe

**How can we reproduce it?:**

> Craft crystals together, get free crystals

**Video**

https://youtu.be/fcoD3yfl02k

No other mods.

The first time it happened, I was in multiplayer in a custom modpack and I don't know how I got a second to start with.  Having only 1 of both types, some kind of weirdness happened with the AM2 magician's workbench and it gave me more, then I could easily dupe them.

**Comment by NPException42** [comment]
Wow... a bit emberassing that I missed that for so long in development. ^^

Thanks for the report!  I'll fix it for the next version of DP.

**Comment by NPException** [comment]
Wow. That simple fix only took more than a year! 😄
