### ISSUE TITLE
Tinkers Construct tools + reading the book

### ISSUE THREAD

**Issue by Aeroxia** [NPException/Dimensional-Pockets#102]
**Dimensional Pockets Version:**

> DimensionalPockets-1.7.10-0.11.4.1-universal

**MinecraftForge Version:**

> 10.13.4.1558

**SSP or SMP? (Client or Server):**

> Client

**Crash Report (via. Pastebin):**

> https://gist.githubusercontent.com/Aeroxia/fd938e8f17cc587a57f2/raw/b3a17fb8418c544d7736fdb4bfd0890d2a1335cf/gistfile1.txt

**What happens / happened?:**

> Crash when you've got the book open and a tinkers construct tool tries to update while in your inventory

**How can we reproduce it?:**

> Add the auto-repair modifier to a tinkers construct tool with ball of moss, and make sure it has damage to be repaired.  Open the book while standing in the sun and wait a few seconds.

This may not be the most important thing in the world, but it was really bugging me not knowing what was going on and took hours to hunt down the source. There seemed to be no pattern, even though I could reliably get it to crash or not crash, but I noticed the index it mentioned was always the same except for once and seemed to be about where my mattock probably was in inventory, and suddenly I had an idea.  Tested it out, and there it is, but how strange!

**Comment by NPException42** [comment]
Thanks for the report! A very strange thing indeed. We'll look into it.

**Comment by NPException** [comment]
I happened to find another report of a crash, but DP was not involved there: http://pastebin.com/raw/iDEATJYs

I'd go so far to say, that this is not actually an issue caused by DP, but by one of the other mods involved (likely TC).
