### ISSUE TITLE
Server crash with enderio fluid conduit

### ISSUE THREAD

**Issue by Saereth** [NPException/Dimensional-Pockets#104]
Running the latest version dim pockets and omniscore, EnderIO 1.7.10 2.3.0.421
forge 1556, also occurs on forge 1558

This happened when extracting from into a dimensional pocket with the enderio fluid conduit, had to mcedit out the connection

Crashlog here,
http://pastebin.com/FvAHw2ZC

If you require an additional information I'll be glad to get it all together for you.

**Comment by NPException42** [comment]
Oh shoot... Thanks for the report! I'll look into as soon as I find the time.

**Comment by Jezza** [comment]
Have you found the time yet?
I really need this fix.
