### ISSUE TITLE
[Feature Request] Small chance to generate vanilla dungeon in Pocket

### ISSUE THREAD

**Issue by NPException** [NPException/Dimensional-Pockets#62]
User Azu on IRC suggested this:

http://minecraft.gamepedia.com/Dungeon

Give a small chance to spawn such a dungeon inside a newly generated pocket, and have the spawnpoint inside it.

What's your opinion on this @Jezza ?

_**[EDIT]**_ So this can get implemented under the premise that it is toggled off by default in the config.
something like this:

`DUNGEON_SPAWN_CHANCE=0 // chance of dungeon spawning for each new pocket in parts per 1000`

**Comment by Jezza** [comment]
No. This just breaks the idea of inside of a pocket.  
I dislike it because I make a pocket to simplify a process, not because I want to fight mobs. I'd say make it a config if you really want it, but I request that it be turned off by default.

**Comment by NPException42** [comment]
Good. I thought the same. So config option with default=false it is.

**Comment by NPException** [comment]
_I'm officially stopping development for Dimensional Pockets._

Feature suggestion scrapped without replacement.
