### ISSUE TITLE
[Feature Request] Alternate recipies for Thaumcraft

### ISSUE THREAD

**Issue by NPException** [NPException/Dimensional-Pockets#64]
User Azu on IRC suggested this.

The idea is to have infusion altar recipes for the DP and the crystals. (Changeable in config of course)
Those recipes should match the difficulty of the default crafting recipes. Therefore they need to take into account the effort it takes to set up the infusion altar in the first place.

**Depends on #63**

**Comment by Jezza** [comment]
I like this, but dislike it.  
If we add thaumcraft recipes, I still want the default recipes enabled. :)

**Comment by Jezza** [comment]
Also, they'll be hard coded, but again, aligned with the level of difficulty crafting. 
* 0 - easy  
* 1 - medium  
* 2 - hard
* 3 - haha

**Comment by NPException42** [comment]
Is there no way for the TC recipes to get configurable?

**Comment by Jezza** [comment]
No, they can be fully customisable, but again, I'd really rather them to not be.

**Comment by NPException42** [comment]
Then my same opinon from #63 applies here. Enforcing a recipe is an unnecessary restriction.

**Comment by NPException** [comment]
_I'm officially stopping development for Dimensional Pockets._

There will likely not be a replacement for this feature suggestion in [Dimensional Pockets 2](https://github.com/NPException/Dimensional-Pockets-2) since the crafting mechanism will be very different.
