### ISSUE TITLE
[Wiki] Fill the wiki with content

### ISSUE THREAD

**Issue by NPException** [NPException/Dimensional-Pockets#66]
- [x] Dimensional Pocket
- [x] Analytics
- [x] Better main page
- [x] Config File
- [x] Guide To Dimensional Pockets
- [x] Nether Crystal
- [x] End Crystal
- [x] Pocket Wrench

**Comment by NPException42** [comment]
started with creating custom side bar for the upcoming content and adding pictures for the items and DP itself
