### ISSUE TITLE
Add ComputerCraft support

### ISSUE THREAD

**Issue by NPException** [NPException/Dimensional-Pockets#90]
Take a look at Lordmau5' mod for reference: https://github.com/Lordmau5/FFS/blob/master/src/main/java/com/lordmau5/ffs/compat/CCPeripheralProvider.java#L23

**Comment by thraaawn** [comment]
I looked into this myself. Sadly it is not possible to implement your own kind of cable at the moment, i.e. this will not work for CCs network cable :(

**Comment by NPException** [comment]
_I'm officially stopping development for Dimensional Pockets._

I took this feature idea over to [Dimensional Pockets 2](https://github.com/NPException/Dimensional-Pockets-2/issues/4).
